server:
  port: 8081
base-url:
  context: /tech-voice
logging:
  level:
    com.poc.techvoice.articleservice: DEBUG
audit:
  user: user-id
task:
  executor:
    pool:
      core-size: 100
      max-size: 100
    queue-capacity: 1000
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech_voice?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root@123
  mail:
    host: smtp.gmail.com
    username: test123@gmail.com
    password: password@123
    port: 587
